### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by O4dg** [ToxicDev-Patryk/ProxyChecker#1]
![IMG_0390](https://github.com/user-attachments/assets/30ce0200-4074-4b6e-9bdc-15bd2ed45333)

Thanks for your work but there is a problem it can't check the http type you said it supports all?

**Comment by ToxicDev-Patryk** [comment]
hi sorry for the problem i put old SRC on github haha i will fix it rn

**Comment by ToxicDev-Patryk** [comment]
Fixed (;

Tested on: Windows and Debian

**Comment by ToxicDev-Patryk** [comment]
If you are getting issue about modules just redownload github repo and use this command "npm install" also it was tested on node v18.16.0 and npm 9.5.1
